# Generated by Django 3.0 on 2020-01-12 03:21

import autoslug.fields
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='boardpost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='')),
                ('Content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('Slug', autoslug.fields.AutoSlugField(editable=False, populate_from='Content')),
                ('Tag', models.CharField(max_length=200)),
                ('Post_Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
