# Generated by Django 3.0 on 2020-01-12 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webboard', '0004_boardpost_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardpost',
            name='author',
        ),
    ]
