# Generated by Django 3.0 on 2020-01-16 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webboard', '0007_auto_20200116_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardpost',
            name='Author',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
