# Generated by Django 3.0 on 2020-01-20 16:27

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webboard', '0010_boardcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardcomment',
            name='comment',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
