# Generated by Django 2.2.6 on 2019-11-30 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('image_url', models.CharField(max_length=2083)),
                ('S_reviewer', models.BooleanField(default=False)),
                ('sign_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
