# Generated by Django 2.2.6 on 2019-11-30 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='image_url',
            field=models.CharField(blank=True, max_length=2083, null=True),
        ),
    ]
