# Generated by Django 3.0 on 2020-01-27 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200127_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_image',
            field=models.ImageField(default='media/userprofile.png', upload_to=''),
        ),
    ]
