# Generated by Django 3.0 on 2020-01-12 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='reviewmovie',
            name='director',
            field=models.ManyToManyField(to='webpage.Director'),
        ),
    ]
