# Generated by Django 3.0 on 2020-01-12 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0002_auto_20200112_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='reviewmovie',
            name='actor',
            field=models.ManyToManyField(to='webpage.Actor'),
        ),
    ]
