# Generated by Django 3.0 on 2020-01-13 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0003_auto_20200112_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewmovie',
            name='actor',
        ),
        migrations.AddField(
            model_name='reviewmovie',
            name='actor',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.RemoveField(
            model_name='reviewmovie',
            name='director',
        ),
        migrations.AddField(
            model_name='reviewmovie',
            name='director',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.DeleteModel(
            name='Actor',
        ),
        migrations.DeleteModel(
            name='Director',
        ),
    ]
