# Generated by Django 3.0 on 2020-01-13 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0006_auto_20200113_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmovie',
            name='actor',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='reviewmovie',
            name='director',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='reviewmovie',
            name='score',
            field=models.FloatField(),
        ),
    ]
