# Generated by Django 3.0 on 2020-01-13 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0007_auto_20200113_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmovie',
            name='score',
            field=models.FloatField(default='0'),
        ),
    ]
