# Generated by Django 3.0 on 2020-01-13 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0008_auto_20200113_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmovie',
            name='movie_image',
            field=models.CharField(max_length=2535),
        ),
    ]
