# Generated by Django 3.0 on 2020-01-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0009_auto_20200113_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmovie',
            name='movie_image',
            field=models.ImageField(upload_to='image'),
        ),
    ]
