# Generated by Django 3.0 on 2020-01-13 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0010_auto_20200113_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmovie',
            name='movie_image',
            field=models.CharField(max_length=2538),
        ),
    ]
