# Generated by Django 3.0 on 2020-01-13 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0012_auto_20200113_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmovie',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
