# Generated by Django 3.0 on 2020-01-13 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0014_auto_20200113_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewmovie',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, default='300', editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='reviewmovie',
            name='movie_image',
            field=models.ImageField(height_field='image_height', upload_to='movieimage'),
        ),
    ]
