# Generated by Django 3.0 on 2020-01-13 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0015_auto_20200113_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmovie',
            name='movie_image',
            field=models.ImageField(height_field='image_height', upload_to='image'),
        ),
    ]
