# Generated by Django 3.0 on 2020-01-19 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0024_comment_replytext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='replytext',
            field=models.TextField(default=None, null=True),
        ),
    ]
